In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from pathlib import Path

In [2]:
turn_folder = Path("../pilot_llm_evaluation_turn/csv/")
holistic_folder = Path("../pilot_llm_evaluation_holistic/csv/")

## Make Turn Dataset

In [12]:
# Make Turn Dataset


# find all csv files that contain 'ALL' in the filename
all_files = list(turn_folder.glob("*ALL*.csv"))

print(f"Found {len(all_files)} files:")
for f in all_files:
    print(" -", f.name)

# read and combine
data = [pd.read_csv(f) for f in all_files]
turn_df = pd.concat(data, ignore_index=True)

print("Combined shape:", turn_df.shape)

Found 9 files:
 - L10_frustrated_multi.ALL_TURNS.csv
 - L5_neutral_multi.ALL_TURNS.csv
 - L5_angry_multi.ALL_TURNS.csv
 - L1_frustrated_multi.ALL_TURNS.csv
 - L1_neutral_multi.ALL_TURNS.csv
 - L1_angry_multi.ALL_TURNS.csv
 - L5_frustrated_multi.ALL_TURNS.csv
 - L10_angry_multi.ALL_TURNS.csv
 - L10_neutral_multi.ALL_TURNS.csv
Combined shape: (225, 6)

In [4]:
turn_df.head()

,scenario_id,judge_model,turn,metric_id,number_id,score
0,L10_frustrated_multi,Qwen/Qwen3-30B-A3B-Instruct-2507-FP8,1,tone_appropriateness,1,5
1,L10_frustrated_multi,Qwen/Qwen3-30B-A3B-Instruct-2507-FP8,1,emotional_calibration_accuracy,2,5
2,L10_frustrated_multi,Qwen/Qwen3-30B-A3B-Instruct-2507-FP8,1,emotional_escalation_moral_framing,3,5
3,L10_frustrated_multi,Qwen/Qwen3-30B-A3B-Instruct-2507-FP8,1,functional_integration_of_empathy,4,5
4,L10_frustrated_multi,Qwen/Qwen3-30B-A3B-Instruct-2507-FP8,1,contextual_appropriateness_of_emotional_framing,5,5

In [13]:
# Map scenario codes to condition names (group_id)
code_to_group = {
    "L1_frustrated_multi": "Group A",
    "L5_neutral_multi": "Group A",
    "L10_angry_multi": "Group A",

    "L1_neutral_multi": "Group B",
    "L5_angry_multi": "Group B",
    "L10_neutral_multi": "Group B",

    "L1_angry_multi": "Group C",
    "L5_frustrated_multi": "Group C",
    "L10_frustrated_multi": "Group C",
}

turn_df.insert(2,'group_id', 2)
turn_df['group_id'] = turn_df['scenario_id'].map(code_to_group)
turn_df['group_id'].value_counts(dropna=False)

group_id
Group C    75
Group A    75
Group B    75
Name: count, dtype: int64

## Make Holistic Dataset

In [15]:
# Make Turn Dataset


# find all csv files that contain 'ALL' in the filename
all_files = list(holistic_folder.glob("*ALL*.csv"))

print(f"Found {len(all_files)} files:")
for f in all_files:
    print(" -", f.name)

# read and combine
holistic = [pd.read_csv(f) for f in all_files]
hol_df = pd.concat(holistic, ignore_index=True)

print("Combined shape:", hol_df.shape)

Found 3 files:
 - ALL_emotional_adaptivity_holistic.csv
 - ALL_emotional_coherence_holistic.csv
 - ALL_problem_resolution_holistic.csv
Combined shape: (27, 6)

In [16]:
hol_df.insert(2,'group_id', 2)
hol_df['group_id'] = hol_df['scenario_id'].map(code_to_group)
hol_df['group_id'].value_counts(dropna=False)

group_id
Group A    9
Group C    9
Group B    9
Name: count, dtype: int64

In [17]:
hol_df.head()

,scenario_id,judge_model,group_id,turn,metric_id,number_id,score
0,L10_angry_multi,Qwen/Qwen3-30B-A3B-Instruct-2507-FP8,Group A,0,emotional_adaptivity,7,5
1,L10_frustrated_multi,Qwen/Qwen3-30B-A3B-Instruct-2507-FP8,Group C,0,emotional_adaptivity,7,4
2,L10_neutral_multi,Qwen/Qwen3-30B-A3B-Instruct-2507-FP8,Group B,0,emotional_adaptivity,7,4
3,L1_angry_multi,Qwen/Qwen3-30B-A3B-Instruct-2507-FP8,Group C,0,emotional_adaptivity,7,5
4,L1_frustrated_multi,Qwen/Qwen3-30B-A3B-Instruct-2507-FP8,Group A,0,emotional_adaptivity,7,4

# Save as CSV

In [18]:
hol_df.to_csv('llm_holistic.csv', index=False)
turn_df.to_csv('llm_turn.csv', index=False)